In [78]:
#1st Question
import numpy as np
arr=np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [28]:
# 2nd Question
x=[]
y=[]
for i in range(5):
    x.append(int(input()))
for j in range(5):
    y.append(int(input()))
a=np.array(x)
b=np.array(y)
c=np.concatenate((a,b),axis=None)
c

10
9
8
7
6
5
43
2
1
1


array([10,  9,  8,  7,  6,  5, 43,  2,  1,  1])

In [32]:
np.sort(a)

array([ 6,  7,  8,  9, 10])

In [33]:
np.sort(b)

array([ 1,  1,  2,  5, 43])

In [34]:
np.sort(c)

array([ 1,  1,  2,  5,  6,  7,  8,  9, 10, 43])

In [ ]:
# 3rd question
If a is an array of n dimensions.
y=a.shape()  #gives the dimension of array in format(x1,x2.........,xn) (touple)
n=list(y)    #converts touple into list
s=1
for i in n:
    s=s*n[i]
s

In [36]:
# example
a=np.arange(16).reshape(2,2,2,2)
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [40]:
y=a.shape
y

(2, 2, 2, 2)

In [43]:
n=list(y)
n

[2, 2, 2, 2]

In [48]:
s=1
for i in n:
    s=s*n[i]
s

16

In [62]:
#4th question
a=np.array([1,2,3,4,5,6])
print(a.shape)
a_newaxis=a[:,np.newaxis]   ##using np.newaxis
print(a_newaxis)
a_newaxis.shape

(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [59]:
a_newaxis=a[np.newaxis,:]
print(a_newaxis)
a_newaxis.shape    #using np.newaxis

[[1 2 3 4 5 6]]


(1, 6)

In [63]:
a_expandims=np.expand_dims(a,axis=0)  #using np.expand_dims
print(a_expandims)             
a_expandims.shape

[[1 2 3 4 5 6]]


(1, 6)

In [64]:
a_expandims=np.expand_dims(a,axis=1)  #using np.expand_dims
print(a_expandims)             
a_expandims.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [66]:
a_reshape=a.reshape(2,3)    #using reshape
print(a_reshape)
a_reshape.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [67]:
a_reshape=a.reshape(3,2)    #using reshape
print(a_reshape)
a_reshape.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [75]:
#5th question
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
vs=np.vstack((x,y))                   #### vertical stacking
vs

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [76]:
hs=np.hstack((x,y))                 #### horizontal stacking
hs

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#6th Question
We can get unique items present in list or touple or array by convering the specific data structure into set.
We can count the unique items by including the collections library ,in which we use Counter function to get the count of unique
items in the form of dictionary.

In [77]:
#### example
import collections as coll
a=np.array([7,0,2,2,4,0,0,7,6,7])
b=set(a)
print(b)
count=coll.Counter(a)
count

{0, 2, 4, 6, 7}


Counter({7: 3, 0: 3, 2: 2, 4: 1, 6: 1})